[package]
name = "pastebin"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.8.0"
rusqlite = {version = "0.25" , features = ["bundled"] }
rand = "0.8"
actix-files = "0.5"
serde = { version = "1.0", features = ["derive"] }
tera = "1.20.0"